apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: lamm-tk-tls
spec:
  secretName: lamm-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.elperrogordo.tk
  dnsNames:
    - testing.elperrogordo.tk
    - www.elperrogordo.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - www.elperrogordo.tk 
          - testing.elperrogordo.tk
