apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: luisalfredomunozmolina-tk-tls
spec:
  secretName: luisalfredomunozmolina-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: elperrogordo.tk
  dnsNames:
    - elperrogordo.tk
    - www.elperrogordo.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - elperrogordo.tk
          - www.elperrogordo.tk 